AllCops:
  Exclude:
    - spec/dummy/bin/*
    - spec/dummy-*/**/*
  TargetRubyVersion: 2.5

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/spec_helper.rb

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*

Style/MultilineIfModifier:
  Exclude:
    - spec/support/dummy_app_helpers.rb
Style/WhileUntilModifier:
  Exclude:
    - spec/support/dummy_app_helpers.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/*.rake

Style/MixinUsage:
  Exclude:
    - lib/tasks/*.rake

Metrics/AbcSize:
  Exclude:
    - lib/generators/**/*

Metrics/LineLength:
  Max: 130
