name: Lint and test

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install sqlite3
        run: sudo apt-get install -y libsqlite3-dev
      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
        - rails: '6.0'
          ruby: '3.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.versions.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.versions.ruby }}
      - name: Install sqlite3
        run: sudo apt-get install -y libsqlite3-dev
      - name: Install nodejs dependencies
        run: |
          cd spec/dummy_${{ matrix.versions.rails }}
          npm install
      - name: Build
        run: |
          export RAILS_VERSION=${{ matrix.versions.rails }}
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: RSpec
        run: RAILS_VERSION=${{ matrix.versions.rails }} bundle exec rspec
